language: python
branches:
  only:
  - master

virtualenv:
  system_site_packages: false
# Install the codecov pip dependency
install:
 - pip install -r requirements.txt
 - pip install pytest-cov
 - pip install codecov

services:
  - docker
before_install:
  - docker pull python:3.7-alpine

script: 
  - pytest --cov=./
  - docker build -t car_app:0 --build-arg PORT=80 --build-arg WORKERS=2 .

# Push the results back to codecov
after_success:
  - codecov